services:
  - type: web
    name: crypto-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python your_bot_file_name.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-bot-db
          property: connectionString
      - key: CRYPTO_BOT_TOKEN
        sync: false
      - key: CRYPTO_OWNER_ID
        sync: false
      - key: WEBHOOK_MODE
        value: "true"
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: crypto-trading-bot
          property: url
      - key: ENVIRONMENT
        value: production
